#=================================================================================
#This file was generated by a particle effect generator created by Fan_Fan_tom.
#You can learn how to use it through the link below:
#這個檔案是由 FanFantom 製作的粒子效果生成器產生的
#你可以點底下的連結學習如何使用
#https://github.com/FanFantom9452/MinecraftParticleGenerator
#=================================================================================
#粒子效果名稱 : electric_spark
#粒子特效參數 : 0 0 0 0 1 force @a[distance=..50]
#是否自動幫特效經過的實體加上tag? : No
#每個粒子效果加上tag的偵測半徑 : 1
#起始角度 : 0
#初始座標偏差 (XYZ) : (0, 0, 0)
#所有機械手臂要旋轉幾次 : 36
#每次旋轉的座標偏差 : (0, 0, 0)
#機械手臂的數量 : 1
#第 1 個機械手臂的長度和旋轉角度 : 1 , 10
particle electric_spark ~1 ~0 ~0 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.98 ~0 ~0.17 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.94 ~0 ~0.34 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.87 ~0 ~0.5 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.77 ~0 ~0.64 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.64 ~0 ~0.77 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.5 ~0 ~0.87 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.34 ~0 ~0.94 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.17 ~0 ~0.98 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0 ~0 ~1 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.17 ~0 ~0.98 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.34 ~0 ~0.94 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.5 ~0 ~0.87 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.64 ~0 ~0.77 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.77 ~0 ~0.64 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.87 ~0 ~0.5 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.94 ~0 ~0.34 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.98 ~0 ~0.17 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-1 ~0 ~0 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.98 ~0 ~-0.17 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.94 ~0 ~-0.34 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.87 ~0 ~-0.5 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.77 ~0 ~-0.64 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.64 ~0 ~-0.77 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.5 ~0 ~-0.87 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.34 ~0 ~-0.94 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~-0.17 ~0 ~-0.98 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0 ~0 ~-1 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.17 ~0 ~-0.98 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.34 ~0 ~-0.94 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.5 ~0 ~-0.87 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.64 ~0 ~-0.77 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.77 ~0 ~-0.64 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.87 ~0 ~-0.5 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.94 ~0 ~-0.34 0 0 0 0 1 force @a[distance=..50]
particle electric_spark ~0.98 ~0 ~-0.17 0 0 0 0 1 force @a[distance=..50]
